/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openEntry from "./open_entry";
export type { openEntry };
import type * as paid from "./paid";
export type { paid };
