networks:
    default: development
    mainnet:
      host: "https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID"
    goerli:
      host: "https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID"
dotenv: .env
compiler:
    solc:
        version: 0.8.17
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - '@ERC721A=chiru-labs/ERC721A@4.2.3'
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
dependencies:
    - chiru-labs/ERC721A@4.2.3
    - OpenZeppelin/openzeppelin-contracts@4.8.0
