networks:
    default: development
dependencies:
    - solidstate-network/solidstate-solidity@0.0.51
    - chiru-labs/ERC721A-Upgradeable@4.2.3
compiler:
    evm_version: null
    solc:
        version: 0.8.17
        remappings:
            - '@solidstate=solidstate-network/solidstate-solidity@0.0.51'
            - '@chiru-labs-upgradeable=chiru-labs/ERC721A-Upgradeable@4.2.3'

