networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        reverting_tx_gas_limit: max
        default_contract_owner: true
dependencies:
    - solidstate-network/solidstate-solidity@0.0.51
compiler:
    evm_version: null
    solc:
        version: 0.8.17
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - '@solidstate=solidstate-network/solidstate-solidity@0.0.51'
console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs
reports:
    only_include_project: true
hypothesis:
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true
autofetch_sources: false
dev_deployment_artifacts: false
