networks:
    default: development
dependencies:
    - solidstate-network/solidstate-solidity@0.0.51
compiler:
    evm_version: null
    solc:
        version: 0.8.17
        remappings:
            - '@solidstate=solidstate-network/solidstate-solidity@0.0.51'
