networks:
    default: development
dependencies:
    - solidstate-network/solidstate-solidity@0.0.51
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0
    - chiru-labs/ERC721A-Upgradable@4.2.3
compiler:
    evm_version: null
    solc:
        version: 0.8.17
        remappings:
            - '@solidstate=solidstate-network/solidstate-solidity@0.0.51'
            - '@chiru-labs=chiru-labs/ERC721A-Upgradable@4.2.3'
            - '@openzeppeling-upgradable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0'

