networks:
    default: development
    mainnet:
      host: "https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID"
    goerli:
      host: "https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID"
dotenv: .env
compiler:
    solc:
        version: "0.8.17"
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - '@erc721a=chiru-labs/ERC721A@4.2.3'
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
            - '@openzeppelinUpgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1'
            - '@solidstate=solidstate-network/solidstate-solidity@0.0.51'
            - '@zksync=c0dejax/v2-testnet-contracts@0.1.1'
            - '@chainlink=smartcontractkit/chainlink@1.13.0'
dependencies:
    - chiru-labs/ERC721A@4.2.3
    - OpenZeppelin/openzeppelin-contracts@4.8.0
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1
    - solidstate-network/solidstate-solidity@0.0.51
    - c0dejax/v2-testnet-contracts@0.1.1
    - smartcontractkit/chainlink@1.13.0
