networks:
    default: development
    mainnet:
      host: "https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID"
    goerli:
      host: "https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID"
dotenv: .env
compiler:
    solc:
        version: "0.8.17"
        viaIR: True
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
            - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1/contracts'
            - '@solidstate=solidstate-network/solidstate-solidity@0.0.51'
            - '@matterlabs/zksync-contracts=c0dejax/v2-testnet-contracts@.0.2.0'
            - '@chainlink=smartcontractkit/chainlink@2.3.0'
            - '@chiru-labs=chiru-labs/ERC721A-Upgradeable@4.2.3'
dependencies:
    - chiru-labs/ERC721A@4.2.3
    - OpenZeppelin/openzeppelin-contracts@4.8.0
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1
    - solidstate-network/solidstate-solidity@0.0.51
    - c0dejax/v2-testnet-contracts@.0.2.0
    - smartcontractkit/chainlink@2.3.0
    - chiru-labs/ERC721A-Upgradeable@4.2.3
