dependencies:
    - chiru-labs/ERC721A@4.2.3
    - OpenZeppelin/openzeppelin-contracts@4.8.0
networks:
    default: development
compiler:
    solc:
        version: 0.8.17
        remappings:
            - '@ERC721A=chiru-labs/ERC721A@4.2.3'
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'

