/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IL1NaffleBase,
  IL1NaffleBaseInterface,
} from "../../../../interfaces/naffle/ethereum/IL1NaffleBase";

const _abi = [
  {
    inputs: [],
    name: "NotSupported",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_l2BlockNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "_l2TxNumberInBlock",
        type: "uint16",
      },
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "_proof",
        type: "bytes32[]",
      },
    ],
    name: "consumeSetWinnerMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_ethTokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_nftId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_paidTicketSpots",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_ticketPriceInWei",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_endTime",
        type: "uint256",
      },
      {
        internalType: "enum NaffleTypes.NaffleType",
        name: "_naffleType",
        type: "uint8",
      },
    ],
    name: "createNaffle",
    outputs: [
      {
        internalType: "uint256",
        name: "naffleId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "txHash",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IL1NaffleBase__factory {
  static readonly abi = _abi;
  static createInterface(): IL1NaffleBaseInterface {
    return new utils.Interface(_abi) as IL1NaffleBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL1NaffleBase {
    return new Contract(address, _abi, signerOrProvider) as IL1NaffleBase;
  }
}
