/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControl from "./access_control";
export type { accessControl };
import type * as ownable from "./ownable";
export type { ownable };
