/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondBase__factory } from "./DiamondBase__factory";
export { IDiamondBase__factory } from "./IDiamondBase__factory";
