/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export interface IL2PaidTicketBaseInterface extends utils.Interface {
  functions: {
    "mintTickets(address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "refundAndBurnTickets(uint256,uint256[],address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "mintTickets" | "refundAndBurnTickets"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "mintTickets",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "refundAndBurnTickets",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundAndBurnTickets",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IL2PaidTicketBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IL2PaidTicketBaseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    mintTickets(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _naffleId: PromiseOrValue<BigNumberish>,
      ticketPriceInWei: PromiseOrValue<BigNumberish>,
      startingTicketId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    refundAndBurnTickets(
      _naffleId: PromiseOrValue<BigNumberish>,
      _naffleTicketIds: PromiseOrValue<BigNumberish>[],
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  mintTickets(
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _naffleId: PromiseOrValue<BigNumberish>,
    ticketPriceInWei: PromiseOrValue<BigNumberish>,
    startingTicketId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  refundAndBurnTickets(
    _naffleId: PromiseOrValue<BigNumberish>,
    _naffleTicketIds: PromiseOrValue<BigNumberish>[],
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    mintTickets(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _naffleId: PromiseOrValue<BigNumberish>,
      ticketPriceInWei: PromiseOrValue<BigNumberish>,
      startingTicketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    refundAndBurnTickets(
      _naffleId: PromiseOrValue<BigNumberish>,
      _naffleTicketIds: PromiseOrValue<BigNumberish>[],
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    mintTickets(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _naffleId: PromiseOrValue<BigNumberish>,
      ticketPriceInWei: PromiseOrValue<BigNumberish>,
      startingTicketId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    refundAndBurnTickets(
      _naffleId: PromiseOrValue<BigNumberish>,
      _naffleTicketIds: PromiseOrValue<BigNumberish>[],
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintTickets(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _naffleId: PromiseOrValue<BigNumberish>,
      ticketPriceInWei: PromiseOrValue<BigNumberish>,
      startingTicketId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    refundAndBurnTickets(
      _naffleId: PromiseOrValue<BigNumberish>,
      _naffleTicketIds: PromiseOrValue<BigNumberish>[],
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
