/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as diamond from "./diamond";
export { IProxy__factory } from "./IProxy__factory";
export { Proxy__factory } from "./Proxy__factory";
