/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondWritable__factory } from "./DiamondWritable__factory";
export { DiamondWritableInternal__factory } from "./DiamondWritableInternal__factory";
export { IDiamondWritable__factory } from "./IDiamondWritable__factory";
export { IDiamondWritableInternal__factory } from "./IDiamondWritableInternal__factory";
