/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControl } from "./AccessControl";
export type { AccessControlInternal } from "./AccessControlInternal";
export type { IAccessControl } from "./IAccessControl";
export type { IAccessControlInternal } from "./IAccessControlInternal";
