/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Internal } from "./IERC1155Internal";
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { IERC165 } from "./IERC165";
export type { IERC173 } from "./IERC173";
export type { IERC173Internal } from "./IERC173Internal";
export type { IERC721 } from "./IERC721";
export type { IERC721Internal } from "./IERC721Internal";
export type { IERC721Receiver } from "./IERC721Receiver";
