/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondFallback__factory } from "./DiamondFallback__factory";
export { IDiamondFallback__factory } from "./IDiamondFallback__factory";
