/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export declare namespace NaffleTypes {
  export type OpenEntryTicketStruct = {
    naffleId: PromiseOrValue<BigNumberish>;
    ticketIdOnNaffle: PromiseOrValue<BigNumberish>;
    winningTicket: PromiseOrValue<boolean>;
  };

  export type OpenEntryTicketStructOutput = [BigNumber, BigNumber, boolean] & {
    naffleId: BigNumber;
    ticketIdOnNaffle: BigNumber;
    winningTicket: boolean;
  };
}

export interface L2OpenEntryTicketViewInterface extends utils.Interface {
  functions: {
    "getAdminRole()": FunctionFragment;
    "getL2NaffleContractAddress()": FunctionFragment;
    "getOpenEntryTicketById(uint256)": FunctionFragment;
    "getOwnerOfNaffleTicketId(uint256,uint256)": FunctionFragment;
    "getTotalSupply()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getAdminRole"
      | "getL2NaffleContractAddress"
      | "getOpenEntryTicketById"
      | "getOwnerOfNaffleTicketId"
      | "getTotalSupply"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAdminRole",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getL2NaffleContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenEntryTicketById",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerOfNaffleTicketId",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAdminRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getL2NaffleContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenEntryTicketById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerOfNaffleTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupply",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TicketsAttachedToNaffle(uint256,uint256[],uint256,address)": EventFragment;
    "TicketsDetachedFromNaffle(uint256,uint256[],uint256[])": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsAttachedToNaffle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsDetachedFromNaffle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  operator: string;
  tokenId: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface TicketsAttachedToNaffleEventObject {
  naffleId: BigNumber;
  ticketIds: BigNumber[];
  startingTicketId: BigNumber;
  owner: string;
}
export type TicketsAttachedToNaffleEvent = TypedEvent<
  [BigNumber, BigNumber[], BigNumber, string],
  TicketsAttachedToNaffleEventObject
>;

export type TicketsAttachedToNaffleEventFilter =
  TypedEventFilter<TicketsAttachedToNaffleEvent>;

export interface TicketsDetachedFromNaffleEventObject {
  naffleId: BigNumber;
  ticketIds: BigNumber[];
  ticketIdsOnNaffle: BigNumber[];
}
export type TicketsDetachedFromNaffleEvent = TypedEvent<
  [BigNumber, BigNumber[], BigNumber[]],
  TicketsDetachedFromNaffleEventObject
>;

export type TicketsDetachedFromNaffleEventFilter =
  TypedEventFilter<TicketsDetachedFromNaffleEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  tokenId: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface L2OpenEntryTicketView extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L2OpenEntryTicketViewInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAdminRole(overrides?: CallOverrides): Promise<[string]>;

    getL2NaffleContractAddress(overrides?: CallOverrides): Promise<[string]>;

    getOpenEntryTicketById(
      _ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[NaffleTypes.OpenEntryTicketStructOutput]>;

    getOwnerOfNaffleTicketId(
      _naffleId: PromiseOrValue<BigNumberish>,
      _ticketIdOnNaffle: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTotalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getAdminRole(overrides?: CallOverrides): Promise<string>;

  getL2NaffleContractAddress(overrides?: CallOverrides): Promise<string>;

  getOpenEntryTicketById(
    _ticketId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<NaffleTypes.OpenEntryTicketStructOutput>;

  getOwnerOfNaffleTicketId(
    _naffleId: PromiseOrValue<BigNumberish>,
    _ticketIdOnNaffle: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getAdminRole(overrides?: CallOverrides): Promise<string>;

    getL2NaffleContractAddress(overrides?: CallOverrides): Promise<string>;

    getOpenEntryTicketById(
      _ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<NaffleTypes.OpenEntryTicketStructOutput>;

    getOwnerOfNaffleTicketId(
      _naffleId: PromiseOrValue<BigNumberish>,
      _ticketIdOnNaffle: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "TicketsAttachedToNaffle(uint256,uint256[],uint256,address)"(
      naffleId?: PromiseOrValue<BigNumberish> | null,
      ticketIds?: null,
      startingTicketId?: null,
      owner?: PromiseOrValue<string> | null
    ): TicketsAttachedToNaffleEventFilter;
    TicketsAttachedToNaffle(
      naffleId?: PromiseOrValue<BigNumberish> | null,
      ticketIds?: null,
      startingTicketId?: null,
      owner?: PromiseOrValue<string> | null
    ): TicketsAttachedToNaffleEventFilter;

    "TicketsDetachedFromNaffle(uint256,uint256[],uint256[])"(
      naffleId?: PromiseOrValue<BigNumberish> | null,
      ticketIds?: null,
      ticketIdsOnNaffle?: null
    ): TicketsDetachedFromNaffleEventFilter;
    TicketsDetachedFromNaffle(
      naffleId?: PromiseOrValue<BigNumberish> | null,
      ticketIds?: null,
      ticketIdsOnNaffle?: null
    ): TicketsDetachedFromNaffleEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
  };

  estimateGas: {
    getAdminRole(overrides?: CallOverrides): Promise<BigNumber>;

    getL2NaffleContractAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getOpenEntryTicketById(
      _ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOwnerOfNaffleTicketId(
      _naffleId: PromiseOrValue<BigNumberish>,
      _ticketIdOnNaffle: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAdminRole(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getL2NaffleContractAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOpenEntryTicketById(
      _ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOwnerOfNaffleTicketId(
      _naffleId: PromiseOrValue<BigNumberish>,
      _ticketIdOnNaffle: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
