/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { L1NaffleAdmin } from "./L1NaffleAdmin";
export type { L1NaffleBase } from "./L1NaffleBase";
export type { L1NaffleBaseInternal } from "./L1NaffleBaseInternal";
export type { L1NaffleDiamond } from "./L1NaffleDiamond";
export type { L1NaffleView } from "./L1NaffleView";
