/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondReadable } from "./DiamondReadable";
export type { IDiamondReadable } from "./IDiamondReadable";
